language: python
install:
  - pip install -U pip setuptools wheel coveralls
  - pip install -r requirements.txt
  - python manage.py collectstatic --no-input
before_script:
  - "export DATABASE_URL=sqlite:///:memory"
script:
  - coverage run manage.py test
after_success:
  - coveralls
